config/routes.rb
Rails.application.routes.draw do
  resources :attendees
  resources :events
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/showevent/:uri', to: 'events#uri_find'
  get '/create', to: 'events#new'
  get '/checkin/:uri', to: 'attendees#checkin'
  get '/about', to: 'static#about'
  
  root 'static#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  #Next line makes sure that you can't check in twice to the same event
  validates_with NoDuplicateValidator
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }


end

app/models/concerns/no_duplicate_validator.rb
class NoDuplicateValidator < ActiveModel::Validator
  def validate(record)
    event = Event.find(record.event_id) 
    event.attendees.each do |a|
      if record.email.downcase == a.email.downcase
        record.errors.add(:email, "You can't check in twice to the same event (duplicate email)")
      end
    end
  end
end

app/models/concerns/time_validator.rb
require 'date'

class TimeValidator < ActiveModel::Validator
  def validate(record)
    if record.start > record.end
      record.errors.add(:start, "Event must start before it ends")
    end

    if record.end < DateTime.now
      record.errors.add(:end, "Event must not end before present time")
    end
  end
end

app/models/concerns/unique_uri.rb
class UniqueUri < ActiveModel::Validator
  def validate(record)
    @event = Event.find_by_uri(record.uri)
    if @event != nil
      record.errors.add(:uri, "taken already")
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :location, presence:true, length: { maximum: 100 }
  validates_with TimeValidator
  validates :creator, presence: true, length: { maximum: 50 }
  validates :contact_email, length: { maximum: 255 },
                            format: { with: VALID_EMAIL_REGEX }
  validates :uri, presence: true, length: { maximum: 150 },
                            format: { with: /\A[a-zA-Z0-9]+\z/, message: "can't contain whitespace or invalid chars" }
  validates_with UniqueUri

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]

  # GET /attendees
  # GET /attendees.json
  #def index
  #  @attendees = Attendee.all
  #end

  # GET /attendees/1
  # GET /attendees/1.json
  #def show
  #end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  #def edit
  #end

  # POST /attendees
  # POST /attendees.json
  def create
    #@attendee = Attendee.new(attendee_params)
    event = Event.find_by(uri: attendee_params[:event_uri])
    id = event.id
    #attendee_params = ActionController::Parameters.new({name: attendee_params[:name], email: attendee_params[:email], event_id: id})
    @attendee = Attendee.new({email: attendee_params[:email], name: attendee_params[:name], event_id: id})
 

    respond_to do |format|
      if @attendee.save 
        format.html { redirect_to "/showevent/#{event.uri}", notice: nil }
        format.json { render :show, status: :created}
      else
        format.html { redirect_to "/showevent/#{event.uri}", notice: @attendee.errors}
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
=begin
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
=begin
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: 'Attendee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:name, :email, :event_uri)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @event = Event.new
    
    respond_to do |format|
      format.html { render :new }
    end
    #now = DateTime.now()
    #@events = Event.order(:start).select { |e| now < e.end}
  end

  # GET /events/1
  # GET /events/1.json
  #def show
  #end

  def uri_find
    @event = Event.find_by_uri(params[:uri])
    if @event == nil
      uri = params[:uri]
      @event = Event.new

      respond_to do |format|
        format.html { render :new }
      end
      #render :new, notice: 'Sorry, event URI #{uri} invalid'
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  #def edit
  #end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: nil }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
=begin
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
=end
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
   #@event.attendees do |a|
   #  a.destroy
   #end
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :start, :end, :creator, :contact_email, :uri)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
  def fix_uri(url, uri)
    url.split('/')[0]+"/showevent/#{uri}"
  end
end

app/helpers/events_helper.rb
require 'date'
module EventsHelper
  def time_until(start_t, end_t)
    now = DateTime.now
    if now < start_t and day_gap(start_t, end_t) > 0
      days = day_gap(start_t, end_t)
      return "Starts in #{days} #{"day".pluralize(days)}"
    elsif now < start_t
      return "Starts at #{start_t.to_time}"
    elsif now < end_t
      return "Ends at #{end_t.to_time}"
    else
      return "Event Over"
    end   
  end

  def day_gap(start_t, end_t)
    (start_t.to_date - end_t.to_date).to_int
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/attendees/_form.html.erb
<%= form_with(model: attendee, local: true) do |form| %>
  <% if attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendees/dep.edit.html.erb
<h1>Editing Attendee</h1>

<%= render 'form', attendee: @attendee %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/dep.index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.name %></td>
        <td><%= attendee.email %></td>
        <td><%= attendee.event %></td>
        <td><%= link_to 'Show', attendee %></td>
        <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
        <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/dep.new.html.erb
<h1>New Attendee</h1>

<%= render 'form', attendee: @attendee %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/dep.show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attendee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @attendee.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= @attendee.event %>
</p>

<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>

app/views/events/_attendee_form.html.erb
<%= form_with(model: attendee, local: true) do |form| %>
  <% if attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-center left">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field text-center left">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field text-center left">
    <input type="hidden" name="attendee[event_uri]" id="attendee_event_uri" value="<%= @event.uri%>">
  </div>

  <div class="actions text-center">
    <input type="submit" name="name" value="Check In" data-disable-with="Create Attendee">
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
  <div class="center">
    <div id="error_explanation">
      <h2 class=""><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class="text-center">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="text-center">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="text-center">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="text-center">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="text-center">
    <%= form.label :creator %>
    <%= form.text_field :creator %>
  </div>

  <div class="text-center">
    <%= form.label :contact_email %>
    <%= form.text_field :contact_email %>
  </div>

  <div class="text-center">
    <%= form.label :uri %>
    <%= form.text_field :uri %>
  </div>  

  <div class="text-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/dep.edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/dep.index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<p class="text-muted">This page is inteneded for debugging purposes only, and will not be included in the production build</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Starts In</th>
      <th>Creator</th>
      <th>Contact email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %>  </td>
        <td><%= event.location %>  </td>
        <td><%= time_until(event.start, event.end) %> </td>
        <td><%= event.creator %>  </td>
        <td><%= event.contact_email %>  </td>
        <td><%= link_to 'Show', event %>  </td>
        <td><%= link_to 'Edit', edit_event_path(event) %> </td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>  </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="jumbotron">
  <p id="notice"><%= notice %></p>
  <h4 class="display-4 text-center">New Event</h4>
  <p class="lead text-center">
    <%= render 'form', event: @event %>
  </p>
</div>

app/views/events/show.html.erb
<div class="jumbotron">
  <h4 class="display-3 text-center">Event Created Successfully!</h4>
  <p class="lead big text-center">
    Here's Your Checkin URL!
    <br>
     <a href="<%=url_for(only_path: false, controller: 'events', action:'uri_find', uri: @event.uri)%>"><%=url_for(only_path: false, controller: 'events', action:'uri_find', uri: @event.uri)%></a>
  </p>
  <p class="lead text-muted up text-center">Give this url to your attendees so they can check in!</p>
</div>

app/views/events/uri_find.html.erb
<div class="jumbotron">
   <% if notice != nil %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% notice.each do |message| %>
        <li><%= message[0] + ": " + message[1][0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h4 class="display-3 text-center"><%= @event.name %></h4>
  <div class="container">
    <div class="row">
      <div class="col-8">
        <div class="event-param left-content text-right">
          <h4 class="text-center">Details</h4>
          <div class="text-center">
            <label>
              When?
            </label>
            <var>
              <%= @event.start %>
            </var>
          </div>
          <div class="text-center">
            <label>
              Where?
            </label>
            <var>
              <%= @event.location %>
            </var>
          </div>
          <div class="text-center">
            <label>
              Contact:
            </label>
            <var>
              <a href="mailto:<%= @event.contact_email %>"><%= @event.creator %></a>
            </var>
          </div>
          <hr>
          <h5 class="text-center">Check In</h5>
          <p class="">
            <%= render 'attendee_form', attendee: Attendee.new %>
          </p>
          <%= link_to 'Delete Event', 
             event_path(@event), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' } %> 
        </div>
      </div>
      <div class="col-4">
        <h4>Attendees</h4>
        <% @event.attendees.each do |attendee| %>
          <p class="down name"><%= attendee.email %> <br> <%=attendee.created_at.to_s %></p>
        <% end %>
      </div>
  </div>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Manage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-expand-lg navbar-default navbar-fixed-top bg-light">
  <a class="navbar-brand" href="/">E-Manage</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/about">About<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Manage
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/create">New Event</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
  <body>
    <div class="indent">
      <%= yield %>
    </div>
  </body>
  
</html>